apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gpsd-kafka-broker
  labels:
    app: {{ .Release.Name }}-gpsd-kafka-broker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gpsd-kafka-broker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-gpsd-kafka-broker
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      initContainers:
        - name: wait-for-dns
          image: busybox:1.34
          command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-gpsd-kafka-broker.{{ .Values.namespace }}.svc.cluster.local; do echo waiting for DNS; sleep 2; done;']
      containers:
        - name: gpsd-kafka-broker
          image: "{{ .Values.broker.image.repository }}:{{ .Values.broker.image.tag }}"
          imagePullPolicy: {{ .Values.broker.image.pullPolicy }}
          ports:
            {{- range .Values.broker.service }}
            - containerPort: {{ .targetPort }}
              name: {{ .name }}
            {{- end }}
          env:
            - name: KAFKA_BROKER_ID
              value: "{{ .Values.broker.config.brokerId }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://{{ .Release.Name }}-gpsd-kafka-broker.{{ .Values.namespace }}.svc.cluster.local:29092,PLAINTEXT_HOST://{{ .Release.Name }}-gpsd-kafka-broker.{{ .Values.namespace }}.svc.cluster.local:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "{{ .Values.broker.config.replicationFactor }}"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "{{ .Values.broker.config.replicationFactor }}"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_NODE_ID
              value: "{{ .Values.broker.config.nodeId }}"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "{{ .Values.broker.config.nodeId }}@{{ .Release.Name }}-gpsd-kafka-broker.{{ .Values.namespace }}.svc.cluster.local:29093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LOG_DIRS
              value: "{{ .Values.broker.config.logDirs }}"
            - name: CLUSTER_ID
              value: "{{ .Values.broker.config.clusterId }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.broker.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.broker.config.logDirs }}
          {{- end }}
      {{- if .Values.broker.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-gpsd-kafka-broker-pvc
      {{- end }}